### PR TITLE
[16.0][FIX] stock_picking_report_valued: Fix delivery slip report if product has a HS Code

### PR DESCRIPTION
**Pull request by tuantrantg**

### CODE REVIEW

**Review by dzungtran89 — APPROVED** [review]
lgtm

image

**Comment by dzungtran89** [comment]
ah, I missed one thing, please bump the version to "16.0.1.0.1", for patch

**Comment by nilshamerlinck** [comment]
actually no, the bump will be done by the oca bot at merge

**Comment by dzungtran89** [comment]
Ok

**Pull request closed without merging**
